name: Continuous Deployment

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # borrowed from: https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/20
  # fail_if_pull_request_is_draft:
  #   if: github.event.pull_request.draft == true
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Fail in order to indicate that Pull Request needs to be marked as Ready for Review before CI/CD pipeline can run.
  #     run: exit 1

  deploy:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@v2

      - name: Configure git
        run: |
          git config --global user.email "bot@interwebalchemy.com"
          git config --global user.name "Interweb Alchemy Release Bot"

      - name: Install dependencies
        run: bun install

      # - name: Run Tests
      #   run: bun test

      - name: Build
        run: bun run build

      - name: Semantic Release
        if: github.ref == 'refs/heads/main'
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
